name: unbaja_parking_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  get: 4.6.5
  flutter: 
    sdk: flutter
  cloud_firestore: ^3.1.17

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

